version: '3'
services:
  api:
    hostname: api
    build:
      dockerfile: Dockerfile.local
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
